name: dockerize CI - Pytest

on:
    push:
        branches: [develop]
    pull_request:
        branches: [develop]
jobs:
    test1:
        runs-on: ubuntu-latest

        steps:
            - name: checkout code
              uses: actions/checkout@v4
            - name: setup Docker buildx
              uses: docker/setup-buildx-action@v3
            - name: build Docker image
              run: |
                docker build -t devops-lab .
            - name: run tests inside Docker container
              run: | 
                docker run --rm -v ${{ github.workspace }}:/app devops-lab
            - name: Upload test report
              uses: actions/upload-artifact@v4
              with:
                name: pytest-report
                path: report.html