name: Build and push Docker hub with certain image number

on:
    push:
        tags:
            - 'v*' #只在push tag開頭是v的時候觸發

jobs:
    build-and-push-to-hub:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Extract version from tag
              id: extract_tag
              run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
            
            - name: Setup Docker buildx
              uses: docker/setup-buildx-action@v3
            
            - name: Login to Docker hub
              uses: docker/login-action@v3
              with:
                username: ${{secrets.DOCKER_USERNAME}} 
                password: ${{secrets.DOCKER_PASSWORD}}
            
            - name: Build and push Docker image
              uses: docker/build-push-action@v5
              with:
                context: .
                push: true
                tags: |
                    unforsaken/devops-lab:latest
                    unforsaken/devops-lab:${{ env.VERSION }}
